name: Build

on:
  workflow_dispatch:
    inputs:
      onnxruntime-version:
        description: "ONNX Runtime version"
        type: string
  push:
    tags:
      - v*.*.*

env:
  GCC_VERSION: 10
  CMAKE_VERSION: 3.26
  PYTHON_VERSION: 3.9
  NODE_VERSION: 20
  XCODE_VERSION: 14.2
  MACOSX_DEPLOYMENT_TARGET: 10.15

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-aarch64-static_lib
            runs-on: ubuntu-22.04
            cross-compile: x86-aarch64
            build: >
              CMAKE_OPTIONS="-D CMAKE_TOOLCHAIN_FILE=$(pwd)/onnxruntime/cmake/linux_arm64_crosscompile_toolchain.cmake -D onnxruntime_ENABLE_CPUINFO=OFF -D CMAKE_CXX_COMPILER=$CXX -D CMAKE_C_COMPILER=$CC"
              PARALLEL_JOB_COUNT=2
              ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: linux-aarch32-static_lib
            runs-on: ubuntu-22.04
            cross-compile: x86-aarch32
            build: >
              CMAKE_OPTIONS="-D CMAKE_TOOLCHAIN_FILE=$(pwd)/onnxruntime/cmake/linux_arm32_crosscompile_toolchain.cmake -D onnxruntime_ENABLE_CPUINFO=OFF -D CMAKE_CXX_COMPILER=$CXX -D CMAKE_C_COMPILER=$CC" 
              ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: linux-x64-static_lib
            runs-on: ubuntu-22.04
            cross-compile: false
            build: ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: osx-arm64-static_lib
            runs-on: macos-13-xlarge
            cross-compile: false
            build: ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: osx-universal2-static_lib
            runs-on: macos-13-xlarge
            cross-compile: false
            build: >
              CMAKE_OPTIONS="-D CMAKE_OSX_ARCHITECTURES=arm64;x86_64"
              ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: osx-x86_64-static_lib
            runs-on: macos-13
            cross-compile: false
            build: ./build-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: win-x64-static_lib
            runs-on: windows-2022
            cross-compile: false
            build: ./build-static_lib.sh
            post-build: 7z a $ARCHIVE_DIR/$ARCHIVE_NAME.zip $OUTPUT_DIR/*

          - target: wasm-static_lib
            runs-on: ubuntu-22.04
            cross-compile: false
            build: ./build-wasm-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: wasm-static_lib-simd
            runs-on: ubuntu-22.04
            cross-compile: false
            build: >
              BUILD_OPTIONS="--enable_wasm_simd"
              ./build-wasm-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: wasm-static_lib-threads
            runs-on: ubuntu-22.04
            cross-compile: false
            build: >
              BUILD_OPTIONS="--enable_wasm_threads"
              ./build-wasm-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

          - target: wasm-static_lib-simd-threads
            runs-on: ubuntu-22.04
            cross-compile: false
            build: >
              BUILD_OPTIONS="--enable_wasm_simd --enable_wasm_threads"
              ./build-wasm-static_lib.sh
            post-build: tar -czvf $ARCHIVE_DIR/$ARCHIVE_NAME.tgz -C $OUTPUT_DIR .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GCC
        id: setup-gcc
        if: runner.os == 'Linux' && matrix.cross-compile == 'false'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ env.GCC_VERSION }}

      - name: Setup GCC (cross compile x86-aarch64)
        if: matrix.cross-compile == 'x86-aarch64' && steps.setup-gcc.outcome != 'success'
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          tar xf $(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          rm $(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          echo PATH=$(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH >> $GITHUB_ENV
          echo CC=$(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnueabihf-gcc >> $GITHUB_ENV
          echo CXX=$(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnueabihf-g++ >> $GITHUB_ENV
          echo AR=$(pwd)/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnueabihf-ar >> $GITHUB_ENV

      - name: Setup GCC (cross compile x86-aarch32)
        if: matrix.cross-compile == 'x86-aarch32' && steps.setup-gcc.outcome != 'success'
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
          tar xf $(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
          rm $(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
          echo PATH=$(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin:$PATH >> $GITHUB_ENV
          echo CC=$(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc >> $GITHUB_ENV
          echo CXX=$(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ >> $GITHUB_ENV
          echo AR=$(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-ar >> $GITHUB_ENV

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Setup Python
        id: setup-python
        continue-on-error: true
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python (Linux)
        if: runner.os == 'Linux' && steps.setup-python.outcome	== 'failure'
        run: |
          sudo apt-get update -q -y
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install -q -y \
            python${{ env.PYTHON_VERSION }} \
            python${{ env.PYTHON_VERSION }}-distutils \
            python${{ env.PYTHON_VERSION }}-venv
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python${{ env.PYTHON_VERSION }} 1

      - name: Install Python (macOS)
        if: runner.os == 'macOS' && steps.setup-python.outcome	== 'failure'
        run: brew install python@${{ env.PYTHON_VERSION }}

      - name: Setup Node
        if: startsWith(matrix.target, 'wasm')
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Xcode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Set ONNX Runtime version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/v') }}; then
            echo ONNXRUNTIME_VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_ENV
          elif [ -n "${{ inputs.onnxruntime-version }}" ]; then
            echo ONNXRUNTIME_VERSION=${{ inputs.onnxruntime-version }} >> $GITHUB_ENV
          else
            echo ONNXRUNTIME_VERSION=$(cat ONNXRUNTIME_VERSION) >> $GITHUB_ENV
          fi

      - name: Set environment variables
        run: |
          echo OUTPUT_DIR=./output >> $GITHUB_ENV
          echo ARCHIVE_DIR="${{ runner.temp }}" >> $GITHUB_ENV
          echo ARCHIVE_NAME=onnxruntime-${{ matrix.target }}-${{ env.ONNXRUNTIME_VERSION }} >> $GITHUB_ENV
          echo CROSS_COMPILE=${{ matrix.cross-compile }} >> $GITHUB_ENV

      - name: Build
        run: ${{ matrix.build }}

      - name: Post build
        run: ${{ matrix.post-build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_DIR }}/${{ env.ARCHIVE_NAME }}.*

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          omitName: true
          body: "Official Release: [ONNX Runtime ${{ github.ref_name }}](https://github.com/microsoft/onnxruntime/releases/tag/${{ github.ref_name }})"
          artifacts: "*/*.*"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          omitDraftDuringUpdate: false
